// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTKrBDSVW2OPi974v5Of3LGQoEtia6VY',
    appId: '1:162224605506:web:dfc9c065f37dfa859360db',
    messagingSenderId: '162224605506',
    projectId: 'flutterprectis',
    authDomain: 'flutterprectis.firebaseapp.com',
    storageBucket: 'flutterprectis.firebasestorage.app',
    measurementId: 'G-ZXYCMYT9K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6_4LGzdMlYvIIUvMusGHhmdEUwpYAAQ',
    appId: '1:162224605506:android:6e63fbf8af1d35d89360db',
    messagingSenderId: '162224605506',
    projectId: 'flutterprectis',
    storageBucket: 'flutterprectis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIv66lSQ_nKa-_haabI1A8ww7Bx9ptCbI',
    appId: '1:162224605506:ios:8b79d669c9e7f5639360db',
    messagingSenderId: '162224605506',
    projectId: 'flutterprectis',
    storageBucket: 'flutterprectis.firebasestorage.app',
    iosBundleId: 'com.example.firebasecli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIv66lSQ_nKa-_haabI1A8ww7Bx9ptCbI',
    appId: '1:162224605506:ios:8b79d669c9e7f5639360db',
    messagingSenderId: '162224605506',
    projectId: 'flutterprectis',
    storageBucket: 'flutterprectis.firebasestorage.app',
    iosBundleId: 'com.example.firebasecli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYTKrBDSVW2OPi974v5Of3LGQoEtia6VY',
    appId: '1:162224605506:web:e962b22ac6f4ab879360db',
    messagingSenderId: '162224605506',
    projectId: 'flutterprectis',
    authDomain: 'flutterprectis.firebaseapp.com',
    storageBucket: 'flutterprectis.firebasestorage.app',
    measurementId: 'G-B5JYQWHS5P',
  );
}
